title: COVID-19 Transit Ridership
logo: /assets/img/Chicago_El_(1454110066).jpg
description: A clustering analysis of ridership changes among U.S. transit operators in 2020.
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
